### ISSUE TITLE
Bug : 폴더의 이름을 string으로 받을 경우

### ISSUE THREAD

**Issue by NullXeronier** [LHEALP/Runthm#1]
Resources 폴더에 있는 폴더 이름을 입력해주세요.
--> 이 경우에는 input box의 string이 완전히 일치하지 않으면 Error가 나게 됩니다.

폴더내의 파일을 로드해서 리스트 뷰로 바꾸거나 아니면 

드롭다운 메뉴에 item을 update하는 방향으로 하면 좋을 것 같습니다.

**Comment by LHEALP** [comment]
의견 감사드립니다.

당시 해당 문제를 인지하고 있었으나 12월 안에 마무리 짓기 위해 생략하였습니다.
또한 유니티 리듬게임 및 에디터의 업데이트 계획은 현재로서 가지고 있지 않습니다.

그 대신 게임과 에디터의 병합, 조금 더 품질있는 코드로 프로젝트를 새로 진행하여 업로드 할 계획을 가지고 있습니다.
그때는(?) 제시해주신 방향 잘 기억하여 반영토록 하겠습니다.

감사합니다.

<br/><br/><br/><br/><br/><br/>
(새로 만드는게 나을 거 가타ㅏ요..)
