### ISSUE TITLE
인스펙터 Sheet Editor 미싱

### ISSUE THREAD

**Issue by GodGodGodYongJae** [LHEALP/Runthm#2]
FileIO 쪽에서 Sheet Editor 부분이 누락되어 업로드 된 것 같습니다.
리듬게임 제작에 대한 지식이 전무한데 덕분에 올려주신 소스 덕분에 갈피를 찾게 되어 감사합니다.
다시 한번 에디터 및 리듬게임 소스 공유 정말 감사드리고 잘 쓰겠습니다!

**Comment by LHEALP** [comment]
안녕하세요.
알려주셔서 감사합니다.
유니티를 git으로 관리하다보면 인스펙터 캐싱이 미싱나는 경우가 있는 모양입니다.

아래 이유로 실제 확인 및 조치하지 않지만, 혹시 해결에 어려움을 겪는 다른 분들이 있을 수도 있으니 남겨두겠습니다.

1. 하이어라키에 있는 FileIO 의 익스펙터 항목중 SheetEditor칸에 
2. 하이어라키에 있는 SheetEditor 를 끌어다 놓아 주세요.

에디터가 UnityRhythmGame에 7월 중 업데이트됩니다.
게임과 에디터 코드는 처음부터 다시 작성하지만 설계/구현은 거의 동일하게 이어갈 예정입니다.

마지막으로 도움이 되었다니 감사드립니다.
